import Head from 'next/head'
import React from 'react'

export default function AboutMePage() {
  return (
    <>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container max-w-3xl'>
        <h1 className='text-4xl font-extrabold'>About me</h1>
        <div>
          Comming soon...
        </div>
      </main>
    </>
  )
}
